make.vcf.R: Fixed matching of chrom to FASTA contig ID
GeneDx/scramble pull request #16
Opened 2021-02-12 16:01 UTC by your-highness

In hs37d5 (and other reference fasta files) the sequence identifiers contain contigID and additional information on this contig:
```bash
>1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
>2 dna:chromosome chromosome:GRCh37:2:1:243199373:1
>3 dna:chromosome chromosome:GRCh37:3:1:198022430:1
...
```
Alignment software, _e.g._ `bwa`, strip additional information because most downstream tools can not deal with spaces in contig IDs. 

This pull request matches read FASTA IDs with the contigs from working BAM file.

Fixes #14

2021-02-16 14:44 UTC, rebecca810 requested changes

2021-02-16 14:44 UTC, rebecca810 commented on cluster_analysis/bin/SCRAMble.R
> +    print(mei.winners)
please remove print statement

2021-02-16 14:44 UTC, rebecca810 commented
Thanks for the PR! This is a good improvement.

2021-02-19 16:20 UTC, rebecca810 approved these changes
Many thanks for your contributions!

2021-04-19 19:02 UTC, ulloaa commented
Hello,

Any idea on when this change will be merged? Ideally, a bug-fixing version would be released as well.

thanks

2021-04-19 21:14 UTC, merged

2021-04-19 21:16 UTC, ulloaa commented
Thanks!